config/routes.rb
Rails.application.routes.draw do
  resources :notifies
  resources :gvg_cores do
    collection do
      post 'invite_core'
      get 'accept_core'
      get 'reject_core'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  root to: "home#index"

  get 'sign_up' => 'members#sign_up'
  get 'gvgs' => 'midia_topics#gvgs'
  get 'gvgs/new_gvg' => 'midia_topics#new_gvg', as: :new_gvg
  get 'gvgs/:gvg_id/edit' => 'midia_topics#edit_gvg', as: :edit_gvg
  patch 'gvgs/update' => 'midia_topics#update_gvg', as: :update_gvg
  get 'gvgs/:gvg_id' => 'midia_topics#show_gvg', as: :show_gvg
  post 'gvgs/create_gvg' => 'midia_topics#create_gvg'
  delete 'gvgs/destroy' => 'midia_topics#destroy_gvg', as: :destroy_gvg
  post 'gvgs/create_comment' => 'midia_topics#create_comment', as: :create_comment
  patch 'update_comment' => 'midia_topics#update_comment', as: :update_comment
  delete 'destroy_comment'=> 'midia_topics#destroy_comment', as: :destroy_comment
  get 'recruitment' => 'members#recruitment'
  get 'requests' => 'members#requests'

  resources :events, only: [:index, :create, :update, :destroy] do
    collection do

    end
  end

  resources :itens, only: [:index] do
    collection do
      patch 'update_crafts'
    end
  end

  resources :members, only: [:index] do
    collection do
      get 'log_in'
      get 'accept_request'
      get 'kicked'
      patch 'refuse_request'
      get 'promote_member'
      get 'demote_member'
      get 'show_member'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :items
end

app/models/class_role.rb
class ClassRole < ActiveRecord::Base

has_many :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :midia_topic
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
end

app/models/guild_role.rb
class GuildRole < ActiveRecord::Base

has_many :users

end

app/models/gvg_core.rb
class GvgCore < ActiveRecord::Base
	belongs_to :user, :foreign_key => :user_id
	has_many :users
	has_many :midia_topics
	mount_uploader :avatar, AvatarUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/models/midia_topic.rb
class MidiaTopic < ActiveRecord::Base
	belongs_to :gvg_core
	has_many :comments
	belongs_to :user
end

app/models/notify.rb
class Notify < ActiveRecord::Base
	belongs_to :user
end

app/models/permition.rb
class Permition < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :class_role
  belongs_to :guild_role
  belongs_to :gvg_core
  has_many :comments
  has_many :midia_topics
  has_many :notifies

  has_many :events
  mount_uploader :avatar, AvatarUploader
  
end

app/controllers/gvg_cores_controller.rb
class GvgCoresController < ApplicationController
  before_action :set_gvg_core, only: [:show, :edit, :update, :destroy]

  # GET /gvg_cores
  # GET /gvg_cores.json
  def index
    if !current_user || current_user.status != "1"
      redirect_to new_user_session_path
    end
    @gvg_cores = GvgCore.all
  end

  # GET /gvg_cores/1
  # GET /gvg_cores/1.json
  def show
    if !current_user || current_user.status != "1"
      redirect_to new_user_session_path
    end
  end

  # GET /gvg_cores/new
  def new
    if !current_user || current_user.status != "1"
      redirect_to new_user_session_path
    end
    @gvg_core = GvgCore.new
  end

  # GET /gvg_cores/1/edit
  def edit
    if !current_user || current_user.status != "1"
      redirect_to new_user_session_path
    end
  end

  # POST /gvg_cores
  # POST /gvg_cores.json
  def create
    @gvg_core = GvgCore.new(gvg_core_params)
    @gvg_core.user_id = current_user.id

    respond_to do |format|
      if @gvg_core.save
        current_user.gvg_core_id = @gvg_core.id
        current_user.core_status = 1
        current_user.save
        format.html { redirect_to @gvg_core, notice: 'Gvg core was successfully created.' }
        format.json { render :show, status: :created, location: @gvg_core }
      else
        format.html { render :new }
        format.json { render json: @gvg_core.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gvg_cores/1
  # PATCH/PUT /gvg_cores/1.json
  def update
    respond_to do |format|
      if @gvg_core.update(gvg_core_params)
        format.html { redirect_to @gvg_core, notice: 'Gvg core was successfully updated.' }
        format.json { render :show, status: :ok, location: @gvg_core }
      else
        format.html { render :edit }
        format.json { render json: @gvg_core.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gvg_cores/1
  # DELETE /gvg_cores/1.json
  def destroy
    @gvg_core.destroy
    respond_to do |format|
      format.html { redirect_to gvg_cores_url, notice: 'Gvg core was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invite_core
    user = User.find(params[:user])
    user.core_status = 2
    user.gvg_core = current_user.gvg_core
    if user.save
      render :json => {
        status: "success"
      }
  else
      render :json => {
        status: "failed"
      } 
  end

  end

  def accept_core
    current_user.core_status = 1
    current_user.save
    redirect_to gvg_cores_path
  end

  def reject_core
    if params[:user]
      user = User.find(params[:user])
    else
      user = current_user
    end
    gvg = user.gvg_core
    user.core_status = 3
    user.gvg_core = nil
    user.save
    if params[:user]
      redirect_to gvg
    else
      redirect_to gvg_cores_path
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gvg_core
      @gvg_core = GvgCore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gvg_core_params
      params.require(:gvg_core).permit(:name, :description, :recruiting, :recruiting_description, :avatar, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def interess_list(user)
		list = Array.new
		list << "GvG" if user.gvg
		list << "PK" if user.pk
		list << "ZvZ" if user.zvz
		list << "Gathering" if user.gathering
		list << "Dungeon" if user.dungeons
		list << "Crafting" if user.crafting
		list << "Farming" if user.farming
		list << "Construir Territorios" if user.construct
		list << "Alimentação de Territorios" if user.territory_feed
		list << "Guerra de Castelo" if user.castle
		list << "Barracas" if user.warcamp

		if list.size == 1 
			return list[0] + "."
		elsif list.size == 0
			return " "
		else 
			result = ""
			for i in 0..list.size - 2
				result = result + list[i] + ","
			end
			 result = result + list[list.size - 1] + "."
		end
	end
end

app/helpers/class_role_helper.rb
module ClassRoleHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guild_role_helper.rb
module GuildRoleHelper
end

app/helpers/gvg_cores_helper.rb
module GvgCoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itens_helper.rb
module ItensHelper

	def generatetree
		result = "<ul>"
		Category.where(category_id: nil).each do |category|
			result = generatenode(category, result)
		end
		result += "</ul>"
	end

	def generatenode(father_category, result)
	  result += "<li>" + father_category.name
  	  if father_category.categories or father_category.items
  	  	result += "<ul>"
		father_category.categories.each do |category|
		  result = generatenode(category, result)
		end
  		father_category.items.each do |item|
    	  result += "<li> #{item.name} </li>"
  	 	end
  	 	result += "</ul>"
  	  end
  	  result += "</li>"
  	  return result
	end
end

app/helpers/members_helper.rb
module MembersHelper

end

app/helpers/notifies_helper.rb
module NotifiesHelper
end

app/helpers/permition_helper.rb
module PermitionHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/gvg_cores/_form.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px; margin-bottom: 15px;">Criar novo time GvG</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
      <%= simple_form_for(@gvg_core) do |f| %>
        <%= f.error_notification %>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Nome</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :name, input_html: { class: 'form-control' }, placeholder: "Nome", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Descrição</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :description, input_html: { class: 'form-control' }, placeholder: "Descrição", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Recrutamento Aberto? </label>

      <div class="col-md-6 col-sm-6 col-xs-12" id="gvg_div">
        <%= f.input :recruiting, input_html: { class: 'flat', style:"opacity:0%, position:absolute"}, label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Descrição de Recrutamento </label>

      <div class="col-md-6 col-sm-6 col-xs-12" id="gvg_div">
        <%= f.input :recruiting_description, input_html: { class: 'form-control' }, placeholder: "Descrição", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>


    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Imagem do Core</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <label id="fileupload-example-4-label " for="fileupload-example-4" style="margin-top: 0px">
         <img id="imgDisplay" style="float: left; width: 276px; height: 157px; cursor: pointer; margin: 0px !important; border: 1px solid black"/>
        </label>
                <%= f.input :avatar, label: false, input_html:{class: "", style: "opacity: 0", id: 'fileupload-example-4', onchange:"imagePreview(this)" }  %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>


<script>

  function imagePreview(input){
    if (input.files && input.files[0]) 
        {
          $('#imgDisplay').show();
          var filerdr = new FileReader();
          filerdr.onload = function(e) {
              $('#imgDisplay').attr('src', e.target.result);
          };
          filerdr.readAsDataURL(input.files[0]);
        }
    };

    function imageLoad(){
      $('#imgDisplay').show();
      $('#imgDisplay').attr('src', "<%= @gvg_core.avatar.url %>");
    };
    
  <% if action_name == 'edit' || @gvg_core.errors.any? %>
    imageLoad();
  <% end %>

  </script>





    <div class="ln_solid"></div>

    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
       <%= f.submit "Enviar", class: "btn btn-primary" %>
    </div>
<% end %>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/gvg_cores/edit.html.erb
<%= render 'form' %>

app/views/gvg_cores/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px;">Times de GvG</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="x_panel">

          <% if current_user.gvg_core && current_user.core_status == 1 %>
            <h2> Você já faz parte de um core </h2>
          <% elsif current_user.gvg_core && current_user.core_status == 2 %>
            <h2> Você foi invitado para o time: <%= current_user.gvg_core.name %> <%= link_to "Aceitar",accept_core_gvg_cores_path, class: "btn btn-success" %> <%= link_to "Rejeitar",reject_core_gvg_cores_path, class: "btn btn-danger" %></h2>
          <% elsif current_user.guild_role.permition >= Permition.find(3).permition %>
            <%= link_to "Novo Time",new_gvg_core_path, class: "btn btn-primary" %>
          <% else %>
            <h2> Você precisa ter cargo de warmaster ou superior para criar um novo time de GvG</h2>
          <% end %>

            <div class="row">
              <% @gvg_cores.each do |gvg_core| %>
              <%= link_to gvg_core do %>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail" style="height: 300px;">
                  <%= image_tag gvg_core.avatar.url, style: "height: 61%; width: 100%;" %>
                  <div class="caption">
                    <h3><%= gvg_core.name %></h3>
                    <p>Lider: <%= gvg_core.user.nick %></p>
                    <% if gvg_core.recruiting %>
                    <p>Recrutamento Aberto</p>
                    <% else %>
                    <p>Recrutamento Fechado</p>
                    <% end %>

                  </div>
                </div>
              </div>
              <% end %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gvg_cores/new.html.erb
<%= render 'form' %>

app/views/gvg_cores/show.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px;">Times de GvG: <%= @gvg_core.name %></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="x_panel">
          <div class="col-md-6 col-sm-6 col-xs-6">
            <%= image_tag @gvg_core.avatar.url, style: "width:100%"%>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
            <h5> <strong> Lider: </strong> <%= @gvg_core.user.nick %>
            <h5> <strong> Descrição: </strong> <%= @gvg_core.description %> </h5>
            <h5> <strong>
              <% if @gvg_core.recruiting %>
                Recrutamento Aberto
              <% else %>
                Recrutamento Fechado
              <% end %>
            </strong> </h5>
            <h5> <strong> Descrição do Recrutamento: </strong> <%= @gvg_core.recruiting_description %> </h5>
            <br>
            <br>
            <% if @gvg_core.user == current_user %>
            <%= link_to 'Deletar Time',  @gvg_core,  method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger" %>
            <%= link_to 'Editar Time',  edit_gvg_core_path(@gvg_core), class: "btn btn-default" %>
            <% elsif current_user.gvg_core == @gvg_core %>
              <%= link_to 'Sair do Time',  reject_core_gvg_cores_path, class: "btn btn-danger" %>
            <% end %>
          </div>
          <br>
          <table class="table table-hover" id="members_table">
            <thead>
              <tr> 
                <th> Nick </th>
                <th> Cargo </th>
                <th> Chars Alternativos </th>
                <th> Arma </th>
                <th> Último Login </th>
              </tr>
            </thead>
            <tbody>
              <% @gvg_core.users.where(core_status: 1).each do |user|%>
              <tr>
                <td> <%= user.nick %> 
                  <% if current_user == @gvg_core.user && user != current_user %> 
                    <%= link_to reject_core_gvg_cores_path(user: user) do %>
                      <i class="fa fa-close" style="color: red;"> </i>
                    <%end %>
                  <%end%> 
                </td>
                <td> <%= user.guild_role.name %> </td>
                <td> <%= user.alt1 %>, <%= user.alt2 %> </td>
                <td> <%= user.item_id %> </td>
                <td> <% if user.last_sign_in_at %> <%= user.last_sign_in_at.to_formatted_s(:short) %> <%end%> </td>
                <tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>