config/routes.rb
Rails.application.routes.draw do
  resources :notifies
  resources :gvg_cores do
    collection do
      post 'invite_core'
      get 'accept_core'
      get 'reject_core'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  root to: "home#index"

  get 'sign_up' => 'members#sign_up'
  get 'gvgs' => 'midia_topics#gvgs'
  get 'gvgs/new_gvg' => 'midia_topics#new_gvg', as: :new_gvg
  get 'gvgs/:gvg_id/edit' => 'midia_topics#edit_gvg', as: :edit_gvg
  patch 'gvgs/update' => 'midia_topics#update_gvg', as: :update_gvg
  get 'gvgs/:gvg_id' => 'midia_topics#show_gvg', as: :show_gvg
  post 'gvgs/create_gvg' => 'midia_topics#create_gvg'
  delete 'gvgs/destroy' => 'midia_topics#destroy_gvg', as: :destroy_gvg
  post 'gvgs/create_comment' => 'midia_topics#create_comment', as: :create_comment
  patch 'update_comment' => 'midia_topics#update_comment', as: :update_comment
  delete 'destroy_comment'=> 'midia_topics#destroy_comment', as: :destroy_comment
  get 'recruitment' => 'members#recruitment'
  get 'requests' => 'members#requests'

  resources :events, only: [:index, :create, :update, :destroy] do
    collection do

    end
  end

  resources :itens, only: [:index] do
    collection do
      patch 'update_crafts'
    end
  end

  resources :members, only: [:index] do
    collection do
      get 'log_in'
      get 'accept_request'
      get 'kicked'
      patch 'refuse_request'
      get 'promote_member'
      get 'demote_member'
      get 'show_member'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :items
end

app/models/class_role.rb
class ClassRole < ActiveRecord::Base

has_many :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :midia_topic
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
end

app/models/guild_role.rb
class GuildRole < ActiveRecord::Base

has_many :users

end

app/models/gvg_core.rb
class GvgCore < ActiveRecord::Base
	belongs_to :user, :foreign_key => :user_id
	has_many :users
	has_many :midia_topics
	mount_uploader :avatar, AvatarUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/models/midia_topic.rb
class MidiaTopic < ActiveRecord::Base
	belongs_to :gvg_core
	has_many :comments
	belongs_to :user
end

app/models/notify.rb
class Notify < ActiveRecord::Base
	belongs_to :user
end

app/models/permition.rb
class Permition < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :class_role
  belongs_to :guild_role
  belongs_to :gvg_core
  has_many :comments
  has_many :midia_topics
  has_many :notifies

  has_many :events
  mount_uploader :avatar, AvatarUploader
  
end

app/helpers/class_role_helper.rb
module ClassRoleHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gvg_cores_helper.rb
module GvgCoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itens_helper.rb
module ItensHelper

	def generatetree
		result = "<ul>"
		Category.where(category_id: nil).each do |category|
			result = generatenode(category, result)
		end
		result += "</ul>"
	end

	def generatenode(father_category, result)
	  result += "<li>" + father_category.name
  	  if father_category.categories or father_category.items
  	  	result += "<ul>"
		father_category.categories.each do |category|
		  result = generatenode(category, result)
		end
  		father_category.items.each do |item|
    	  result += "<li> #{item.name} </li>"
  	 	end
  	 	result += "</ul>"
  	  end
  	  result += "</li>"
  	  return result
	end
end

app/helpers/members_helper.rb
module MembersHelper

end

app/helpers/notifies_helper.rb
module NotifiesHelper
end

app/helpers/permition_helper.rb
module PermitionHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Honor n Glory" %> </title>
  <%= favicon_link_tag 'hng.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="nav-md ">
<div class="container body">
  <% flash.each do |key, value| %>
      <div align="center" id="flash" class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<% if current_user %>
<% if current_user.status == "1" %>
<%= render "partials/sidenav" %>
<% end %>
<% end %>
<% if current_user.status != "4" %>
<%= render "partials/topnav" %>
<% end %>
<%= yield %>
  <%= render "partials/footer" %>
  <%= javascript_include_tag 'footermanifest', 'data-turbolinks-track' => true %>
</body>
<% current_user.last_sign_in_at = Time.now if current_user %>
<% current_user.save %>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
<title> Honor n Glory </title>
<%= favicon_link_tag 'hng.ico' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<style>
/*Devise flash*/
.alert-error {
background-color: #f2dede;
border-color: #eed3d7;
color: #b94a48;
text-align: center;
}
.alert-alert {
background-color: #f2dede;
border-color: #eed3d7;
color: #b94a48;
text-align: center;
}
.alert-notice {
background-color: #dff0d8;
border-color: #d6e9c6;
color: #468847;
text-align: left;
}
</style>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="background:#F7F7F7;">
<div class="container body">
<% flash.each do |key, value| %>
<div align="center" id="flash" class="alert alert-<%= key %>">
<a href="#" data-dismiss="alert" class="close">×</a>
<ul style="text-align: center">
<l>
<b> <%= value %> </b>
</l>
</ul>
</div>
<% end %>
<%= yield %>
  <%= javascript_include_tag 'footermanifest', 'data-turbolinks-track' => true %>
</body>

</html>

app/views/partials/_editevent.html.erb
<div class="modal fade" id="editModal_<%= eventq.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editar evento: <%= eventq.title %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(eventq) do |f| %>
          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Título</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :title, input_html: { class: 'form-control' }, placeholder: "Título", label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Descrição</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :description, input_html: { class: 'form-control' }, placeholder: "Descrição", label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Evento Obrigatório? </label>

            <div class="col-md-6 col-sm-6 col-xs-12" id="gvg_div">
              <%= f.input :important, input_html: { class: 'flat', style:"opacity:0%, position:absolute"}, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Data do Evento</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :event_date, input_html: { class: 'form-control', style: "width: 32%; display:inline" }, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Hora de Inicio</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :event_start, input_html: { class: 'form-control', style: "width: 47%; display:inline" }, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Hora de Fim <br><i> (Previsão) </i></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :event_end, input_html: { class: 'form-control', style: "width: 47%; display:inline" }, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" style= "margin-bottom: 0px;">Close</button>
        <%= f.submit "Salvar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_newevent.html.erb
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Criar novo evento</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@event) do |f| %>
          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Título</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :title, input_html: { class: 'form-control' }, placeholder: "Título", label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Descrição</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :description, input_html: { class: 'form-control' }, placeholder: "Descrição", label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Evento Obrigatório? </label>

            <div class="col-md-6 col-sm-6 col-xs-12" id="gvg_div">
              <%= f.input :important, input_html: { class: 'flat', style:"opacity:0%, position:absolute"}, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Data do Evento</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :event_date, input_html: { class: 'form-control', style: "width: 32%; display:inline" }, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Hora de Inicio</label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :event_start, input_html: { class: 'form-control', style: "width: 47%; display:inline" }, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

          <div class="form-group row">
            <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Hora de Fim <br><i> (Previsão) </i></label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.input :event_end, input_html: { class: 'form-control', style: "width: 47%; display:inline" }, label: false %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"> </div>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" style= "margin-bottom: 0px;">Close</button>
        <%= f.submit "Salvar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container ">

  <div class="col-md-3 left_col ">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <%= link_to root_path, class: "site_title" do %><%= image_tag "HnG.png", height: "34px", width:"34px" %> <span>Honor n Glory</span><% end %>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag current_user.avatar.url, :class => "img-circle profile_img", style: "height: 65px; width: 65px;"  %>
        </div>
        <div class="profile_info">
          <span>Bem-vindo,</span>
          <h2><%= current_user.nick %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      
      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu" >

        <div class="menu_section">
          
          <h3 style="margin-top:20px"> <%= current_user.guild_role.name %> </h3>
          <ul class="nav side-menu">
            <li><%= link_to root_path do %> <i class="fa fa-home"></i> Inicio <% end %>
            </li> 

            <li><%= link_to members_path do %><i class="fa fa-user"></i> Membros <% end %>
            </li>


            <li><%= link_to notifies_path do %><i class="fa fa-bullhorn "></i> Comunicados <% end %>
            </li>

            <li><%= link_to events_path do %><i class="fa fa-calendar"></i> Eventos <% end %>
            </li>

            <li><%= link_to gvg_cores_path do %><i class="fa fa-users"></i> Times de GvG <% end %>
            </li>

            <li><%= link_to gvgs_path do %><i class="fa fa-flag-checkered"></i> GvGs <% end %>
            </li>

            <li><%= link_to itens_path do %><i class="fa fa-gavel"></i> Crafters <% end %>
            </li>

            <li><a href="javascript:void(0)"><i class="fa fa-comments-o"></i> Tópicos para Discussão <span class="badge bg-green pull-right">Em breve</span> </a>
            </li>

            <li><a href="javascript:void(0)"><i class="fa fa-photo"></i> Mídia <span class="badge bg-green pull-right">Em breve</span></a>
            </li>

            <% if current_user.recruitment_access || current_user.guild_role.id > 6 %>
            <li><%= link_to requests_path do %><i class="fa fa-users"></i> Requisições Pendentes <% end %>
            </li>
            <% end %>

            <% if current_user.recruitment_access || current_user.guild_role.id > 6 %>
            <li><%= link_to kicked_members_path do %><i class="fa fa-users"></i> Membros Expulsos <% end %>
            </li>
            <% end %>




            

            

            <!--

            <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="form.html">General Form</a>
                </li>
                <li><a href="form_advanced.html">Advanced Components</a>
                </li>
                <li><a href="form_validation.html">Form Validation</a>
                </li>
                <li><a href="form_wizards.html">Form Wizard</a>
                </li>
                <li><a href="form_upload.html">Form Upload</a>
                </li>
                <li><a href="form_buttons.html">Form Buttons</a>
                </li>
              </ul>
            </li>

          -->
            
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag current_user.avatar.url %><%= current_user.nick %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><%= link_to "Alterar Perfil", edit_user_registration_path %>
            </li>
            <li><%= link_to destroy_user_session_path, :method => :delete do %> <i class="fa fa-sign-out pull-right"></i> Log Out <% end %>
            </li>
          </ul>
        </li>
        <!-- 
        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                       <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <a>
                      <span class="image">
                                        <%= image_tag "img.jpg" %>
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>-->

      </ul>
    </nav>
  </div>

</div>
<script>
$('body .dropdown-toggle').dropdown(); 
</script>
<!-- /top navigation -->

app/views/partials/_viewevent.html.erb
<div class="modal fade" id="viewModal_<%= eventq.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="x_content">
          <div class="bs-example" data-example-id="simple-jumbotron">
            <div class="jumbotron">
              <h1><%= eventq.title %></h1>
              <p><%= eventq.description %></p>
            </div>
          </div>
        </div>
        <script>
          function openEditform<%=eventq.id%>(){
            var current_modal = "#viewModal_<%=eventq.id%>";
            var edit_modal = "#editModal_<%=eventq.id%>";
            $(current_modal).modal('hide');
            $(edit_modal).modal('show');
          }
        </script>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" style= "margin-bottom: 0px;">Close</button>
          <% if current_user == eventq.user || current_user.guild_role.permition > eventq.user.guild_role.permition || current_user.guild_role.permition > 6%>
            <button type="button" class="btn btn-primary" onclick="openEditform<%= eventq.id %>()">
              Editar Evento
            </button>
            <%= link_to 'Deletar Evento',  eventq,  method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger" %>
          <% end %>
        </div>
    </div>
  </div>
</div>