config/routes.rb
Rails.application.routes.draw do
  resources :notifies
  resources :gvg_cores do
    collection do
      post 'invite_core'
      get 'accept_core'
      get 'reject_core'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  root to: "home#index"

  get 'sign_up' => 'members#sign_up'
  get 'gvgs' => 'midia_topics#gvgs'
  get 'gvgs/new_gvg' => 'midia_topics#new_gvg', as: :new_gvg
  get 'gvgs/:gvg_id/edit' => 'midia_topics#edit_gvg', as: :edit_gvg
  patch 'gvgs/update' => 'midia_topics#update_gvg', as: :update_gvg
  get 'gvgs/:gvg_id' => 'midia_topics#show_gvg', as: :show_gvg
  post 'gvgs/create_gvg' => 'midia_topics#create_gvg'
  delete 'gvgs/destroy' => 'midia_topics#destroy_gvg', as: :destroy_gvg
  post 'gvgs/create_comment' => 'midia_topics#create_comment', as: :create_comment
  patch 'update_comment' => 'midia_topics#update_comment', as: :update_comment
  delete 'destroy_comment'=> 'midia_topics#destroy_comment', as: :destroy_comment
  get 'recruitment' => 'members#recruitment'
  get 'requests' => 'members#requests'

  resources :events, only: [:index, :create, :update, :destroy] do
    collection do

    end
  end

  resources :itens, only: [:index] do
    collection do
      patch 'update_crafts'
    end
  end

  resources :members, only: [:index] do
    collection do
      get 'log_in'
      get 'accept_request'
      get 'kicked'
      patch 'refuse_request'
      get 'promote_member'
      get 'demote_member'
      get 'show_member'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :items
end

app/models/class_role.rb
class ClassRole < ActiveRecord::Base

has_many :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :midia_topic
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
end

app/models/guild_role.rb
class GuildRole < ActiveRecord::Base

has_many :users

end

app/models/gvg_core.rb
class GvgCore < ActiveRecord::Base
	belongs_to :user, :foreign_key => :user_id
	has_many :users
	has_many :midia_topics
	mount_uploader :avatar, AvatarUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/models/midia_topic.rb
class MidiaTopic < ActiveRecord::Base
	belongs_to :gvg_core
	has_many :comments
	belongs_to :user
end

app/models/notify.rb
class Notify < ActiveRecord::Base
	belongs_to :user
end

app/models/permition.rb
class Permition < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :class_role
  belongs_to :guild_role
  belongs_to :gvg_core
  has_many :comments
  has_many :midia_topics
  has_many :notifies

  has_many :events
  mount_uploader :avatar, AvatarUploader
  
end

app/controllers/midia_topics_controller.rb
class MidiaTopicsController < ApplicationController
	def gvgs
    @gvgs = MidiaTopic.where(midia_type: "gvg")
	end

	def new_gvg
		@midia_topic = MidiaTopic.new
		@midia_topic.user_id = current_user.id
		@midia_topic.midia_type = "gvg"
	end

	def create_gvg
		@midia_topic = MidiaTopic.new(midia_topic_params)
    	@midia_topic.user_id = current_user.id
    	@midia_topic.midia_type = "gvg"
    respond_to do |format|
      if @midia_topic.save
        format.html { redirect_to gvgs_path, notice: 'GvG criada com sucesso.' }
        format.json { render :show, status: :created, location: @midia_topic }
      else
        format.html { render :new }
        format.json { render json: @midia_topic.errors, status: :unprocessable_entity }
      end
    end
	end

  def new_comment
    @comment = Comment.new
    @comment.midia_topic_id = params[:midia_topic_id]
    @midia_topic = params[:midia_topic]
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    midia_topic = MidiaTopic.find(@comment.midia_topic_id)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to show_gvg_path(midia_topic.id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment}
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_comment
    @comment = Comment.find(params[:id])
    @project = params[:id_project]
    @midia_topic = params[:gvg_id]
  end

  def update_comment
    @comment = Comment.find(params[:id])
    midia_topic = MidiaTopic.find(@comment.midia_topic_id)
    @comment.update(comment_params)
    redirect_to show_gvg_path(midia_topic.id), notice: 'Comment was successfully updated.'
  end

  def destroy_comment
    @comment = Comment.find(params[:id])
    midia_topic = MidiaTopic.find(@comment.midia_topic_id)
    @comment.destroy
    redirect_to show_gvg_path(midia_topic.id), notice: 'Comment was successfully destroyed.'
  end 

  def destroy_gvg
    @midia = MidiaTopic.find(params[:id])
    @midia.destroy
    redirect_to gvgs_path
  end

  def edit_gvg
    @midia_topic = MidiaTopic.find(params[:gvg_id])
  end

  def update_gvg
    @midia_topic = MidiaTopic.find(params[:id])
    @midia_topic.update(midia_topic_params)
    redirect_to show_gvg_path(@midia_topic.id), notice: 'GvG atualizada com sucesso.'
  end

  def show_gvg
    @gvg = MidiaTopic.find(params[:gvg_id])
    @comment = Comment.new
  end

	def midia_topic_params
      params.require(:midia_topic).permit(:title, :description, :user_id, :result_hng, :result_other, :enemy, :gvg_core_id, :killboard, :video, :midia_type, :players, :enemies, :map, :gvg_type, :event_date, :event_time)
  end
  def comment_params
      params.require(:comment).permit(:description, :user_id, :midia_topic_id)
end
end

app/helpers/class_role_helper.rb
module ClassRoleHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guild_role_helper.rb
module GuildRoleHelper
end

app/helpers/gvg_cores_helper.rb
module GvgCoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itens_helper.rb
module ItensHelper

	def generatetree
		result = "<ul>"
		Category.where(category_id: nil).each do |category|
			result = generatenode(category, result)
		end
		result += "</ul>"
	end

	def generatenode(father_category, result)
	  result += "<li>" + father_category.name
  	  if father_category.categories or father_category.items
  	  	result += "<ul>"
		father_category.categories.each do |category|
		  result = generatenode(category, result)
		end
  		father_category.items.each do |item|
    	  result += "<li> #{item.name} </li>"
  	 	end
  	 	result += "</ul>"
  	  end
  	  result += "</li>"
  	  return result
	end
end

app/helpers/members_helper.rb
module MembersHelper

end

app/helpers/midia_topics_helper.rb
module MidiaTopicsHelper

end

app/helpers/notifies_helper.rb
module NotifiesHelper
end

app/helpers/permition_helper.rb
module PermitionHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/midia_topics/_form.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px; margin-bottom: 15px;">Criar  GvG</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
      <%= simple_form_for @midia_topic, :url => {controller: "midia_topics", action:"create_gvg"} do |f| %>
        <%= f.error_notification %>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Inimigo</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :enemy, input_html: { class: 'form-control' }, placeholder: "Nome", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Pontuação</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :result_hng, input_html: { class: 'form-control' }, placeholder: "HnG", label: false %>
        <%= f.input :result_other, input_html: { class: 'form-control' }, placeholder: "Inimigo", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Jogadores</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :players, input_html: { class: 'form-control' }, placeholder: "Jogadores", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

        <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Inimigos</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :enemies, input_html: { class: 'form-control' }, placeholder: "Inimigos", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

            <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Mapa</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :map, input_html: { class: 'form-control' }, placeholder: "Mapa", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Tipo de Mapa</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :gvg_type, collection: [ "Construção", "Recursos", "Cidade", "Fazenda"], prompt: "Escolha o Tipo de Mapa", input_html: { class: 'form-control' }, placeholder: "Escolha o Tipo de Mapa", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>  

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Link Killboard</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :killboard, input_html: { class: 'form-control' }, placeholder: "Killboard", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Video</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :video, input_html: { class: 'form-control' }, placeholder: "Video", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Data do Evento</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :event_date, input_html: { class: 'form-control', style: "width: 32%; display:inline" }, label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Horario </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :event_time, input_html: { class: 'form-control', style: "width: 47%; display:inline" }, label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Time de GvG</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.association :gvg_core, collection: GvgCore.all.order(:name), prompt: "Escolha um Core", label_method: :name, input_html: { class: 'form-control' }, placeholder: "Time de GvG", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="ln_solid"></div>

    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
       <%= f.submit "Enviar", class: "btn btn-primary" %>
    </div>
    <% end %>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/midia_topics/edit_gvg.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px; margin-bottom: 15px;">Editar  GvG</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
      <%= simple_form_for @midia_topic, :url => update_gvg_path(id: @midia_topic.id) do |f| %>
        <%= f.error_notification %>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Inimigo</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :enemy, input_html: { class: 'form-control' }, placeholder: "Nome", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Pontuação</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :result_hng, input_html: { class: 'form-control' }, placeholder: "HnG", label: false %>
        <%= f.input :result_other, input_html: { class: 'form-control' }, placeholder: "Inimigo", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Jogadores</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :players, input_html: { class: 'form-control' }, placeholder: "Jogadores", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

        <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Inimigos</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :enemies, input_html: { class: 'form-control' }, placeholder: "Inimigos", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

            <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Mapa</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :map, input_html: { class: 'form-control' }, placeholder: "Mapa", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Tipo de Mapa</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :gvg_type, collection: [ "Construção", "Recursos", "Cidade", "Fazenda"], prompt: "Escolha o Tipo de Mapa", input_html: { class: 'form-control' }, placeholder: "Escolha o Tipo de Mapa", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>  

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Link Killboard</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :killboard, input_html: { class: 'form-control' }, placeholder: "Killboard", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Video</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :video, input_html: { class: 'form-control' }, placeholder: "Video", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Data do Evento</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :event_date, input_html: { class: 'form-control', style: "width: 32%; display:inline" }, label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Horario </label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :event_time, input_html: { class: 'form-control', style: "width: 47%; display:inline" }, label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Time de GvG</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.association :gvg_core, collection: GvgCore.all.order(:name), prompt: "Escolha um Core", label_method: :name, input_html: { class: 'form-control' }, placeholder: "Time de GvG", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="ln_solid"></div>

    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
       <%= f.submit "Enviar", class: "btn btn-primary" %>
    </div>
<% end %>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/midia_topics/gvgs.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px;">GvGs</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="x_panel">
          <% if current_user.guild_role.permition >= Permition.find(4).permition %>
            <%= link_to "Nova GvG", new_gvg_path, class: "btn btn-primary" %>
          <% end %>
        <table class="table table-hover" id="gvgs_table">
        <thead>
          <tr> 
            <th> GvG </th>
            <th> Players </th>
            <th> Inimigos </th>
            <th> Mapa </th>
            <th> Tipo de Mapa </th>
            <th> Core </th>
            <th> Data e Hora </th>
          </tr>
        </thead>
        <tbody>
          
        <% @gvgs.each do |gvg| %>
          <tr>
            <td> HnG <%= gvg.result_hng if gvg.result_hng%> X <%= gvg.result_other if gvg.result_other %> <%= gvg.enemy if gvg.enemy %> <%= link_to show_gvg_path(gvg.id) do %> <i class="fa fa-eye"></i> <% end %></td>
            <td> <%= gvg.players if gvg.players %></td>
            <td> <%= gvg.enemies if gvg.enemies %></td>
            <td> <%= gvg.map if gvg.map %></td>
            <td> <%= gvg.gvg_type if gvg.gvg_type %></td>
            <td> <%= gvg.gvg_core.name if gvg.gvg_core %></td>
            <td> <%= gvg.event_date.to_formatted_s(:short) if gvg.event_date %> <%= gvg.event_time.strftime("%I:%M%p") if gvg.event_time %> </td>
          </tr>
        <% end %>
        </tbody>
      </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$('#gvgs_table').dataTable( {
  paginate: false,
  scrollY: 700
} );
</script>

app/views/midia_topics/new_gvg.html.erb
<%= render 'form' %>

app/views/midia_topics/show_gvg.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px;">GvGs</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        </div>
      </div>
    </div>


    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="x_panel">

          <h2> HnG <%= @gvg.result_hng %> X <%= @gvg.result_other %> <%= @gvg.enemy %> <%if current_user == @gvg.user || current_user.guild_role.permition > 6%>
                  <span> 
                    <%= link_to "", edit_gvg_path(@gvg.id), class: "glyphicon glyphicon-pencil", style: "text-decoration: none" %>
                   </span>
                    <span> <%= link_to '', destroy_gvg_path(id: @gvg.id), method: :delete, class: "glyphicon glyphicon-trash", style: "text-decoration: none", data: { confirm: 'Você tem certeza que deseja excluir essa GvG?'} %> </span>
                  <%end%> </h2>
          <p> <strong> Core: </strong> <%= @gvg.gvg_core.name if @gvg.gvg_core %> <br>
           <strong> Jogadores: </strong> <%= @gvg.players %> <br>
           <strong> Mapa: </strong> <%= @gvg.map if @gvg.map%> <br>
           <strong> Tipo de Mapa: </strong> <%= @gvg.gvg_type if @gvg.gvg_type %> <br>
           <strong> Adversarios: </strong> <%= @gvg.enemies if @gvg.enemies %> <br>
           <strong> Data e Hora: </strong> <%= @gvg.event_date.to_formatted_s(:short) if @gvg.event_date %> <%= @gvg.event_time.strftime("%I:%M%p") if @gvg.event_time %><br>
	         <strong> Killboard: </strong> <a target="_blank" href="<%= @gvg.killboard %>"><%= @gvg.killboard %></a></p>	   
          <div style="position:relative;height:0;padding-bottom:56.25%"> <iframe src="https://www.youtube.com/embed/<%= @gvg.video %>?ecver=2" width="640" height="360" frameborder="0" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe> </div>

          <div style="text-align:left;" id="comments_<%= @gvg.id %>">  
          <ul class="list-unstyled msg_list">
            <% @gvg.comments.each do |comment| %>
              <li style="padding: 5px !important; width: 99% !important">
                <a style="text-decoration: none">
                  <span class="image">
                    <%= image_tag(comment.user.avatar, style: "height: 65px; width: 65px") %>
                  </span>
                  <span>
                    <span><strong><%= comment.user.nick %></strong></span>
                    <span class="time"><%= time_ago_in_words(comment.created_at) %></span>
                  </span>
                  <span class="message">
                          <%= comment.description %>
                  </span>
                </a>
                  <% if comment.user == current_user %>
                  <span> <a href = "#" class="glyphicon glyphicon-pencil drop_icon" data-toggle="modal" data-target="#editcomment_<%= comment.id %>" style= "text-decoration: none !important">  </a>
                  </span>
                  <% end %>
                  <%if current_user == @gvg.user || current_user.guild_role.permition > 6 || comment.user == current_user%>
                    <span> <%= link_to '', destroy_comment_path(id: comment.id), method: :delete, class: "glyphicon glyphicon-trash", style: "text-decoration: none", data: { confirm: 'Você tem certeza que deseja excluir esse comentário?'} %> </span>
                  <%end%>
              </li>
            <% end %>
            </ul>
          </div>
          <%= simple_form_for @comment, :url => create_comment_path(@comment) do |f| %>
            <div class="form-group row">
              <div class="col-md-12 col-sm-6 col-xs-12">
                    <%= f.input :description, input_html: { class: 'form-control' }, placeholder: "Escreva um comentário", label: false %>
              </div>
            </div>
            <%= f.input :midia_topic_id, :as => :hidden, :input_html => {:value =>  @gvg.id} %>
              <div class="actions">
                <%= f.submit "Criar Comentário", class: "btn btn-primary" %>
              </div>
          <% end %>


        </div>
      </div>
    <br>

    <% current_user.comments.each do |comment|%>
      <div class="modal fade" id="editcomment_<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Criar novo evento</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for comment, :url => update_comment_path(:id => comment.id) do |f| %>
        <%= f.input :description, label: false%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" style= "margin-bottom: 0px;">Close</button>
        <%= f.submit "Salvar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <% end %>
        </div>
      </div>
    </div>
  </div>
</div>