config/routes.rb
Rails.application.routes.draw do
  resources :notifies
  resources :gvg_cores do
    collection do
      post 'invite_core'
      get 'accept_core'
      get 'reject_core'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}

  root to: "home#index"

  get 'sign_up' => 'members#sign_up'
  get 'gvgs' => 'midia_topics#gvgs'
  get 'gvgs/new_gvg' => 'midia_topics#new_gvg', as: :new_gvg
  get 'gvgs/:gvg_id/edit' => 'midia_topics#edit_gvg', as: :edit_gvg
  patch 'gvgs/update' => 'midia_topics#update_gvg', as: :update_gvg
  get 'gvgs/:gvg_id' => 'midia_topics#show_gvg', as: :show_gvg
  post 'gvgs/create_gvg' => 'midia_topics#create_gvg'
  delete 'gvgs/destroy' => 'midia_topics#destroy_gvg', as: :destroy_gvg
  post 'gvgs/create_comment' => 'midia_topics#create_comment', as: :create_comment
  patch 'update_comment' => 'midia_topics#update_comment', as: :update_comment
  delete 'destroy_comment'=> 'midia_topics#destroy_comment', as: :destroy_comment
  get 'recruitment' => 'members#recruitment'
  get 'requests' => 'members#requests'

  resources :events, only: [:index, :create, :update, :destroy] do
    collection do

    end
  end

  resources :itens, only: [:index] do
    collection do
      patch 'update_crafts'
    end
  end

  resources :members, only: [:index] do
    collection do
      get 'log_in'
      get 'accept_request'
      get 'kicked'
      patch 'refuse_request'
      get 'promote_member'
      get 'demote_member'
      get 'show_member'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :items
end

app/models/class_role.rb
class ClassRole < ActiveRecord::Base

has_many :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :midia_topic
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
end

app/models/guild_role.rb
class GuildRole < ActiveRecord::Base

has_many :users

end

app/models/gvg_core.rb
class GvgCore < ActiveRecord::Base
	belongs_to :user, :foreign_key => :user_id
	has_many :users
	has_many :midia_topics
	mount_uploader :avatar, AvatarUploader
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/models/midia_topic.rb
class MidiaTopic < ActiveRecord::Base
	belongs_to :gvg_core
	has_many :comments
	belongs_to :user
end

app/models/notify.rb
class Notify < ActiveRecord::Base
	belongs_to :user
end

app/models/permition.rb
class Permition < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :class_role
  belongs_to :guild_role
  belongs_to :gvg_core
  has_many :comments
  has_many :midia_topics
  has_many :notifies

  has_many :events
  mount_uploader :avatar, AvatarUploader
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  layout "login_layout", only: [:sign_up, :recruitment]

	def index 
    if !current_user || current_user.status != "1"
      redirect_to new_user_session_path
    end
		@members = User.where(status: "1")
	end
  def kicked
    @members = User.where(status: "4")
  end

  def show_member
    @user = User.find(params[:user])
  end

	def requests
    if current_user.recruitment_access || current_user.guild_role.id > 6 
      @access = User.where(status: "2")
      @recruitment = User.where(status: "3")
    else
      redirect_to root_path
    end
    if !current_user || current_user.status != "1"
      redirect_to new_user_session_path
    end
	end

	def accept_request
    
    user = User.find(params[:user])
    user.status = 1
    user.guild_role_id = 1
    user.save
    redirect_to requests_path
  end

  def refuse_request
    userparams = params[:user]
    user = User.find(params[:user_id])
    user.status = 4
    user.reason = userparams[:reason]
    user.save
    redirect_to requests_path
  end

  def promote_member
  	user = User.find(params[:user])
    user.guild_role_id = user.guild_role_id + 1
    if user.guild_role_id <= 7
      user.save
      render :json => {
        :user_id => "#{user.id}",
        :guild_role_name => "#{user.guild_role.name}",
        :guild_role_id => "#{user.guild_role.id}"
      }
    end
  end

  def demote_member
  	user = User.find(params[:user])
    user.guild_role_id = user.guild_role_id - 1
    user.save
    if user.guild_role_id >= 1
    render :json => {
      :user_id => "#{user.id}",
      :guild_role_name => "#{user.guild_role.name}",
      :guild_role_id => "#{user.guild_role.id}"
    }
    end
  end
end

app/helpers/class_role_helper.rb
module ClassRoleHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guild_role_helper.rb
module GuildRoleHelper
end

app/helpers/gvg_cores_helper.rb
module GvgCoresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itens_helper.rb
module ItensHelper

	def generatetree
		result = "<ul>"
		Category.where(category_id: nil).each do |category|
			result = generatenode(category, result)
		end
		result += "</ul>"
	end

	def generatenode(father_category, result)
	  result += "<li>" + father_category.name
  	  if father_category.categories or father_category.items
  	  	result += "<ul>"
		father_category.categories.each do |category|
		  result = generatenode(category, result)
		end
  		father_category.items.each do |item|
    	  result += "<li> #{item.name} </li>"
  	 	end
  	 	result += "</ul>"
  	  end
  	  result += "</li>"
  	  return result
	end
end

app/helpers/members_helper.rb
module MembersHelper

end

app/helpers/notifies_helper.rb
module NotifiesHelper
end

app/helpers/permition_helper.rb
module PermitionHelper
end

app/helpers/plainpage_helper.rb
module PlainpageHelper
end

app/views/members/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px;">Membros</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <span> Léndarios: <%= @members.where(account: "Lendária").size %></span> / 
          <span> Épicos: <%= @members.where(account: "Épica").size %></span> / 
          <span> Veteranos: <%= @members.where(account: "Veterana").size %></span>
    <table class="table table-hover" id="members_table">
	<thead>
		<tr> 
			<th> Nick </th>
			<th> Cargo </th>
			<th> Chars Alternativos </th>
			<th> Arma </th>
			<th> Time de GvG </th>
			<th> Último Login </th>
		</tr>
	</thead>
	<tbody>
    
	<% @members.each do |member| %>
  <% if current_user.guild_role.permition > member.guild_role.permition and current_user.guild_role.permition > 6 %>
    <div class="modal fade" id="refuse_member_<%= member.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Expulsar Membro: <%= member.nick %></h4>
                </div>
                <%= simple_form_for member, url: refuse_request_members_path(member,user_id: member.id) do |f| %>
                <div class="modal-body">
                    <div class="form-group row">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Qual motivo da expulsão?</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <%= f.input :reason, input_html: { class: 'form-control', value: '' }, placeholder: "Qual o motivo da expulsão?", label: false %>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12"> </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <%= f.submit "Expulsar Membro", class: "btn btn-danger"%>
                </div>
                <% end %>
              </div>
          </div>
        </div>
    <% end %>
		<tr>
			<td> <%= member.nick %> <%= link_to show_member_members_path(user: member) do %> <i class="fa fa-eye"></i> <% end %> 
        <% if current_user.guild_role.permition > member.guild_role.permition and current_user.guild_role.permition > 6 %>
        <a href="#"class="fa fa-close" data-toggle="modal" data-target="#refuse_member_<%= member.id %>" style="text-decoration: none;">
              </a> <% end %></td>
			<td id="role_<%= member.id %>"><%= member.guild_role.name %>
				<% if user_signed_in? %>
					<% if current_user.guild_role.permition > member.guild_role.permition + 1 %>
							<i class="glyphicon glyphicon-menu-up" style="color: green; cursor:pointer" onclick="promote(<%=member.id%>)"></i>
					<% end %>
					<% if current_user.guild_role.permition > member.guild_role.permition and member.guild_role_id > 1 %>
						<i class="glyphicon glyphicon-menu-down" style="color: red; cursor:pointer" onclick="demote(<%=member.id%>)"></i>
					<% end %>
				<% end %>
			</td>
			<td> <%= member.email %> </td>
			<td> <%= member.item_id %> </td>
			<td id="gvg_core_<%= member.id %>"> <% if member.gvg_core && member.core_status == 1 %>
					<%= member.gvg_core.name %>
          <% elsif member.gvg_core == current_user.gvg_core && member.core_status == 2%>
          Invite Pendente
				 <% else %>
				 	Sem Time de GvG 
          <% if current_user.gvg_core %>
            <% if current_user.gvg_core.user == current_user && member.core_status != 2 %> 
            <i class="fa fa-group" style="color: green; cursor:pointer" onclick="invite(<%= member.id %>)"> </i> <%end%>
  				 <% end %>
         <% end %>
			</td>
			<td> <% if member.last_sign_in_at %> <%= member.last_sign_in_at.to_formatted_s(:short) %> <% end %></td>

		</tr>
	<% end %>
	</tbody>
</table>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
$('#members_table').dataTable( {
  paginate: false,
  scrollY: 700
} );
</script>
<script>
function demote(user_id){
$.ajax({
  type:"GET",
  url:"<%= demote_member_members_path%>",
  dataType:"json",
  data: {user: user_id},
  success:function(result){
  	var role = "role_"+result.user_id;
  	if (result.guild_role_id == 1){
  	document.getElementById(role).innerHTML = result.guild_role_name + " <i class='glyphicon glyphicon-menu-up' style='color: green; cursor:pointer' onclick='promote("+result.user_id+")'> </i>";
  	}else{
  		document.getElementById(role).innerHTML = result.guild_role_name + " <i class='glyphicon glyphicon-menu-up' style='color: green; cursor:pointer' onclick='promote("+result.user_id+")'> </i> <i class='glyphicon glyphicon-menu-down' style='color: red; cursor:pointer' onclick='demote("+result.user_id+")'> </i>";
  	}
  }
})
};

function promote(user_id){
$.ajax({
  type:"GET",
  url:"<%= promote_member_members_path%>",
  dataType:"json",
  data: {user: user_id},
  success:function(result){
  	var role = "role_"+result.user_id;
  	if (result.guild_role_id == <%= current_user.guild_role.permition - 1%>){
  	document.getElementById(role).innerHTML = result.guild_role_name + " <i class='glyphicon glyphicon-menu-down' style='color: red; cursor:pointer' onclick='demote("+result.user_id+")'> </i>";
  	}else{
  		document.getElementById(role).innerHTML = result.guild_role_name + " <i class='glyphicon glyphicon-menu-up' style='color: green; cursor:pointer' onclick='promote("+result.user_id+")'> </i> <i class='glyphicon glyphicon-menu-down' style='color: red; cursor:pointer' onclick='demote("+result.user_id+")'> </i>";
  	}
  }
})
};

function invite(user_id){
$.ajax({
  type:"POST",
  url:"<%= invite_core_gvg_cores_path %>",
  dataType:"json",
  data: {user: user_id},
  success:function(result){
    var core_id = "gvg_core_"+user_id;
    document.getElementById(core_id).innerHTML = "Invite Pendente";
  }
})
};
</script>

app/views/members/kicked.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px;">Membros Expulsos</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="x_panel">
        <table class="table table-hover" id="gvgs_table">
            <thead>
              <tr> 
                <th> Nick </th>
                <th> Cargo </th>
                <th> Razão </th>
                <th> Kickado em </th>
              </tr>
            </thead>
            <tbody>
              
            <% @members.each do |member| %>
          <tr>
            <td> <%= member.nick %> </td>
            <td> <%= member.guild_role.name %> </td>
            <td> <%= member.reason %> </td>
            <td> <%= member.updated_at.to_formatted_s(:short) %> </td>

          </tr>
        <% end %>
        </tbody>
      </table>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$('#gvgs_table').dataTable( {
  paginate: false,
  scrollY: 700
} );
</script>

app/views/members/recruitment.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3 style="margin-left: 20px; margin-top:15px; margin-bottom: 15px;">Recrutamento</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), class: "form-horizontal form-label-left AVAST_PAM_signupform") do |f| %>
  <%= devise_error_messages! %>

    <div class="form-group row">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Nick</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                              <%= f.input :nick, input_html: { class: 'form-control' }, placeholder: "Nick", label: false %>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>
    <div class="form-group row">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Char Alternativo 1</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                              <%= f.input :alt1, input_html: { class: 'form-control' }, placeholder: "Char Alternativo 1", label: false %>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Char Alternativo 2</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                              <%= f.input :alt2, input_html: { class: 'form-control' }, placeholder: "Char Alternativo 2", label: false %>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">E-mail</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :email, input_html: { class: 'form-control' }, placeholder: "E-mail", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
              <% if @validatable %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Senha<br> <i> Mínimo de 8 Digítos </i></label>
      <div class="col-md-6 col-sm-6 col-xs-12">

        <%= f.password_field :password, class: 'form-control', placeholder: "Senha", label: false, autocomplete: "off" %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Confirmar Senha</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmar Senha", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>


    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Interesses / Como pode ajudar a guild</label>

      <div class="col-md-6 col-sm-6 col-xs-12" id="gvg_div">
        <%= f.input :gvg, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "GvG" %>
        <%= f.input :raids, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Raids" %>
        <%= f.input :pk, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "PK" %>
        <%= f.input :zvz, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "ZvZ" %>
        <%= f.input :gathering, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Gathering" %>
        <%= f.input :dungeons, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Dungeons" %>
        <%= f.input :crafting, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Crafting" %>
        <%= f.input :farming, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Farming" %>
        <%= f.input :construct, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Construir Territorios" %>
        <%= f.input :territory_feed, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Alimentação de Territorios" %>
        <%= f.input :castle, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Guerra de Castelos" %>
        <%= f.input :warcamp, input_html: { class: 'flat', style:"opacity:0%, position:absolute" }, label: "Barracas" %>
      </div>


      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>
    
    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Conta</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :account, collection: [ "Lendária", "Épica", "Veterana"], prompt: "Escolha o tipo de conta", input_html: { class: 'form-control' }, placeholder: "E-mail", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>  
        <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Hora de Atividade</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :activity_hour, input_html: { class: 'form-control' }, placeholder: "Hora de Atividade", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>
    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Porque deseja entrar na guild?</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :reason, input_html: { class: 'form-control' }, placeholder: "Porque deseja entrar na guild?", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>

    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Última guild</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :last_guild, input_html: { class: 'form-control' }, placeholder: "Última guild e motivo de saida", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>


    <div class="form-group row">
      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Hora de Atividade</label>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.input :activity_hour, input_html: { class: 'form-control' }, placeholder: "Hora de Atividade", label: false %>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
    </div>
    <div class="ln_solid"></div>

    <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
<p> <b> Ao entrar na guilda você está de acordo com todas as <a target="_blank" href="https://goo.gl/ehbHWw" style="text-decoration: underline"> Regras</a>, lembrando que as mesmas podem ser alteradas em qualquer momento. </b> </p>
       <%= f.submit "Enviar", class: "btn btn-primary" %>
    </div>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/members/requests.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Solicitações</h3>
      </div>
    </div>
    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
			 <h5> <strong> Permissão de Acesso (<%= @access.size%>) </strong> </h5> 
			 <div class="row">
				<% @access.order(:nick).each do |member| %>
				  <div class="col-sm-6 col-md-3">
				    <div class="thumbnail" style="height: 360px">
				      <%= image_tag member.avatar.url, :class => "img-circle profile_img", style: "height: 65px; width: 65px;"  %>
				      <div class="caption">
				        <h3><%= member.nick %></h3>
				        <p> Tipo de Conta: <%= member.account %> </p>
				        <p> Recrutador: <%= member.recruiter %> </p>
				        <p> Interesses: <%= interess_list(member) %> </p>
				        <p> Email: <%= member.email %> </p>				        
				        <p> Alternativos: <%= member.alt1 %>,<%= member.alt2%> </p>
				        <p><%= link_to 'Aceitar', accept_request_members_path(user: member.id), class: "btn btn-primary" %> 
				        	<button type="button" class="btn btn-default" data-toggle="modal" data-target="#refuse_member_<%= member.id %>">
							  Recusar
							</button>
				        </p>
				      </div>
				    </div>
				  </div>
				  <div class="modal fade" id="refuse_member_<%= member.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
					<div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					        <h4 class="modal-title" id="myModalLabel">Recusar Membro: <%= member.nick %></h4>
					      </div>
					      <%= simple_form_for member, url: refuse_request_members_path(member,user_id: member.id) do |f| %>
					      <div class="modal-body">
					        	<div class="form-group row">
							      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Qual motivo da recusa?</label>
							      <div class="col-md-6 col-sm-6 col-xs-12">
							        <%= f.input :reason, input_html: { class: 'form-control', value: '' }, placeholder: "Qual o motivo da recusa?", label: false %>
							      </div>
							      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
							    </div>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					        <%= f.submit "Recusar Membro", class: "btn btn-danger"%>
					      </div>
					      <% end %>
					    </div>
					</div>
				</div>
				<% end %>
			</div>
			 <h5> <strong> Recrutamento (<%= @recruitment.size%>) </strong> </h5> 
			<% @recruitment.each do |member| %>
				<div class="col-sm-6 col-md-3">
				    <div class="thumbnail" style="height: 380px">
				      <%= image_tag member.avatar.url, :class => "img-circle profile_img", style: "height: 65px; width: 65px;"  %>
				      <div class="caption">
				        <h3><%= member.nick %></h3>
				        <p> Razão que deseja entrar na guild: <%= member.reason %> </p>
				        <p> Guild Anterior: <%= member.last_guild %> </p>
				        <p> Tipo de Conta: <%= member.account%> </p>
				        <p> Interesses: <%= interess_list(member) %> </p>
				        <p> Email: <%= member.email %> </p>
				        <p> Alternativos: <%= member.alt1 %>,<%= member.alt2%> </p>

				        <p><%= link_to 'Aceitar', accept_request_members_path(user: member.id), class: "btn btn-primary" %> 
				        	<button type="button" class="btn btn-default" data-toggle="modal" data-target="#refuse_member_<%= member.id %>">
							  Recusar
							</button>				        </p>
				      </div>
				    </div>
				  </div>
				<div class="modal fade" id="refuse_member_<%= member.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
					<div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					        <h4 class="modal-title" id="myModalLabel">Recusar Membro: <%= member.nick %></h4>
					      </div>
					      <%= simple_form_for member, url: refuse_request_members_path(member,user_id: member.id) do |f| %>
					      <div class="modal-body">
					        	<div class="form-group row">
							      <label class="control-label col-md-3 col-sm-3 col-xs-12 control-label-form">Qual motivo da recusa?</label>
							      <div class="col-md-6 col-sm-6 col-xs-12">
							        <%= f.input :reason, input_html: { class: 'form-control', value: '' }, placeholder: "Qual o motivo da recusa?", label: false %>
							      </div>
							      <div class="col-md-3 col-sm-3 col-xs-12"> </div>
							    </div>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					        <%= f.submit "Recusar Membro", class: "btn btn-danger"%>
					      </div>
					      <% end %>
					    </div>
					</div>
				</div>
			<% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>